version: '3.2'
services: 
  selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    # ports:
    #   - "4444:4444"
  # chrome:
  #   image: selenium/node-chrome:3.141.59-yttrium
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
  ting:
    image: u03013112/ting-server
    container_name: 'ting'
    ports:
      - 18004:18004